---
title: "R Notebook"
output: html_notebook
---

## Obtain the IDs for the articles

Also filter or find the way of just including the most recent articles

```{r}
library(RISmed)
search_query <- EUtilsSummary(search_topic, retmax = 50)
medline_object <- EUtilsGet(search_query)
pmid <- ArticleId(medline_object)
```

```{r}
query_to_pmid <- function(query, limit = 50, days_before) {
  search_query <- EUtilsSummary(query, retmax = limit)
  medline_object <- EUtilsGet(search_query)
  ArticleId(medline_object)
}
```


## Use the IDs to obtain the citations

```{r}
library(httr)
library(glue)
library(magrittr)
library(xml2)
library(purrr)

res <- map(pmid, function(id) {
  Sys.sleep(1/3)
  base <- "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
  db <- "pubmed"
  url <- paste0(
    base,
    glue("elink.fcgi?dbfrom={db}&linkname=pubmed_pubmed_refs&id={id}")
  )
  output <- GET(url)
  links <- content(output) %>% 
    xml_contents() %>% 
    xml_find_all("//LinkSetDb/Link") %>% 
    xml_text()
  links
})

```

```{r}
pmid_to_refs <- function(pmid) {
  map(pmid, function(id) {
    Sys.sleep(1/3)
    base <- "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
    db <- "pubmed"
    url <- paste0(
      base,
      glue("elink.fcgi?dbfrom={db}&linkname=pubmed_pubmed_refs&id={id}")
    )
    output <- GET(url)
    links <- content(output) %>% 
      xml_contents() %>% 
      xml_find_all("//LinkSetDb/Link") %>% 
      xml_text()
    links
  })
}
```

## Sort articles by frequency

```{r}
res %>% unlist() %>% table() %>% sort(decreasing = TRUE) %>% .[. > 1]
```

```{r}
refs_to_freqs <- function(refs) {
  freqs <- res %>% 
    unlist() %>% 
    table() %>% 
    sort(decreasing = TRUE) %>% 
    .[. > 1]
  if (length(freqs) > 0) freqs else "There is not enough information to suggest any specific articles"
}
```

## Obtain the name of the article from PMID

```{r}
medline_object <- EUtilsGet("1458460")
ArticleTitle(medline_object)
```


